In [1]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchange its rows and columns (transpose the array)
transposed_array = np.transpose(array)

# Output the original and transposed arrays
print("Original Array:")
print(array)

print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[61 51 58]
 [86 60 50]
 [32 57 90]]

Transposed Array:
[[61 86 32]
 [51 60 57]
 [58 50 90]]


In [2]:
#2. Generate a ID NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np

# Generate a 1D array with 10 elements (IDs)
array = np.arange(1, 11)

# Reshape into a 2x5 array
reshaped_2x5 = array.reshape(2, 5)

# Reshape into a 5x2 array
reshaped_5x2 = array.reshape(5, 2)

# Output the arrays
print("Original 1D Array:")
print(array)

print("\nReshaped 2x5 Array:")
print(reshaped_2x5)

print("\nReshaped 5x2 Array:")
print(reshaped_5x2)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [3]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around it to make a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Output the arrays
print("Original 4x4 Array:")
print(array_4x4)

print("\nArray with Zero Border (6x6):")
print(array_6x6)

Original 4x4 Array:
[[0.89709481 0.48121045 0.96544693 0.92803818]
 [0.05082775 0.85365596 0.69091779 0.36307823]
 [0.0599542  0.99621369 0.53985258 0.89686062]
 [0.92622118 0.96106668 0.21635865 0.45455512]]

Array with Zero Border (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.89709481 0.48121045 0.96544693 0.92803818 0.        ]
 [0.         0.05082775 0.85365596 0.69091779 0.36307823 0.        ]
 [0.         0.0599542  0.99621369 0.53985258 0.89686062 0.        ]
 [0.         0.92622118 0.96106668 0.21635865 0.45455512 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Output the array
print("Array of integers from 10 to 60 with a step of 5:")
print(array)

Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [8]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas'].
#Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)

# Output the transformed arrays
print("Original Array:")
print(array)

print("\nUppercase Array:")
print(uppercase_array)

print("\nLowercase Array:")
print(lowercase_array)

print("\nTitle Case Array:")
print(titlecase_array)

Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Title Case Array:
['Python' 'Numpy' 'Pandas']


In [9]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Create a NumPy array of words
array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_array = np.char.join(' ', array)

# Output the original and spaced arrays
print("Original Array:")
print(array)

print("\nArray with Spaces Between Characters:")
print(spaced_array)

Original Array:
['python' 'numpy' 'pandas']

Array with Spaces Between Characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [10]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
division = np.divide(array1, array2)

# Output the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [11]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Output the identity matrix and diagonal elements
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [12]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

# Output the array of random integers and the prime numbers found
print("Random Integers:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)

Random Integers:
[ 421  335   79  591  845   37  806  405  288  476  108  607  579  716
  962  630  218  753  555  566  364    2  834  996  914  921  215  108
  205  785  880  409   13  459  276  452  577  737  712  553  894  592
  281  326  909  387 1000  586  777  441  836  826  428  974  174  726
  360  707  461  108   28  336  834  819  741  105  565  667  860  269
  467  879  868  347  748   99  799  475  196  332  212  243  517   69
   80  454  499  762  511  698  186  783  862  616  141  538  625  319
  274  771]

Prime Numbers in the Array:
[421  79  37 607   2 409  13 577 281 461 269 467 347 499]


In [13]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For simplicity, let's use random temperatures between 15 and 35 degrees Celsius
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.randint(15, 36, size=30)

# Calculate weekly averages
# There are 4 full weeks in 30 days (28 days) and 2 extra days
weekly_averages = [daily_temperatures[i:i+7].mean() for i in range(0, 28, 7)]

# Add the average for the last incomplete week (last 2 days)
last_week_avg = daily_temperatures[28:].mean()
weekly_averages.append(last_week_avg)

# Display the results
print("Daily Temperatures for the Month (30 Days):")
print(daily_temperatures)
print("\nWeekly Averages:")
for week_num, avg in enumerate(weekly_averages, start=1):
    print(f"Week {week_num}: {avg:.2f}°C")

Daily Temperatures for the Month (30 Days):
[27 30 15 18 18 22 24 34 33 19 21 27 16 21 22 29 32 20 28 23 24 35 34 31
 34 20 30 30 15 33]

Weekly Averages:
Week 1: 22.00°C
Week 2: 24.43°C
Week 3: 25.43°C
Week 4: 30.57°C
Week 5: 24.00°C
